### ISSUE TITLE
Suggestions on the final dataset size for Linear Regressor

### ISSUE THREAD

**Issue by zhipeng-fan** [avinabsaha/ReIQA#11]
Hi! Thanks for sharing this awesome work! Wondering do you guys have some idea on how much data do we needed to train the final linear regressor?

**Comment by avinabsaha** [comment]
Hi @zhipeng-fan,

Thanks for your interest in our work! For the results in the paper, we used datasets of size ~700 (LIVE-IQA) - 40000 (FLIVE).

Datasets upwards of 1000 should be fine for training the final linear regression. However, we find that the more data points, the easier the training of the regressor, as the feature obtained from content and quality-aware modules adds up to 2048*4.  Please consider performing grid search over the hyper-parameters of [ElasticNet](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNet.html) for best performance.

**Comment by avinabsaha** [comment]
Closing this issue, please feel free to re-open if you need to discuss further.
