### ISSUE TITLE
how can i get the final score？ 

### ISSUE THREAD

**Issue by 1193700079** [avinabsaha/ReIQA#3]
<img width="373" alt="image" src="https://github.com/avinabsaha/ReIQA/assets/43908729/9e4fa53f-df8b-4154-9df7-b7d7945a7519">
I'm highly positive about your work and very interested. I would like to ask some questions and hope you can help me! I would like to obtain a final quantitative metric score.

**Comment by avinabsaha** [comment]
Hi @1193700079,

Thanks for your interest in our work! 

We did not release a final regression model as there were too many models (one each for each database) to release.   

Also, the cross-database performance (in general) of IQA models is not great, thus limiting usability on other databases directly. The idea is that we provide the code to extract features and the user can use those features to train any regressor that suits their dataset. This is the recommended way to use Re-IQA. 

We will try to release a regressor trained on one of the databases soon.

**Comment by 1193700079** [comment]
"Thank you, I understand very well! Thank you very much!"
