### ISSUE TITLE
VOC dataset

### ISSUE THREAD

**Issue by ibiii82** [avinabsaha/ReIQA#4]
Could you please provide more detailed information on how you obtained the VOC dataset? It seems like you downloaded the VOC2012 dataset from the link you shared. You appear to have used the data inside the 'JPEGImages' folder. However, that folder contains only 17,125 images, while you seem to have used a total of 33,260 images. How did you obtain the remaining images? For example, files like '2008_000001.jpg' cannot be found in any folder. It would be greatly appreciated if you could clarify this.

**Comment by avinabsaha** [comment]
Hi @ibiii82,

Thanks for your interest in our work!

You have to download both the training/validation and test data (available after creating an account in the evaluation server). 

Let me know if this works out for you.

**Comment by ibiii82** [comment]
Thank you for providing the solution. Thanks to you, I was able to resolve the dataset issue effectively.
