### ISSUE TITLE
How to train on a single server with multiple GPUs

### ISSUE THREAD

**Issue by BingfengHan** [avinabsaha/ReIQA#5]
Hi, thanks for sharing this beautiful work! I don't have different nodes, could you help to offer a script to train model on a single server with multiple GPUs?  :)

**Comment by avinabsaha** [comment]
Hi @BingfengHan ,

You should be able to run the same code with --world-size 1 and --rank 0.

Scale the batch size based on GPU hardware.

**Comment by avinabsaha** [comment]
Closing this issue for now. Feel free to re-open to discuss further.
